(function(_ds){var window=this;var QS=function(a){return!a.classList.contains("material-icons")},YS=async function(a,b){await DevsiteApp.whenReady();const c=_ds.G();var d=DevsiteApp.getInsecureHost();b=b.Z;if(b.origin===c.origin||!d||b.origin===d){try{var e=_ds.cf(_ds.El,b.data)}catch(g){return}d=_ds.Le(e,1);if(4===d)RS(a,b);else{var f=e.getName();if(f&&(f=a.querySelector(`devsite-iframe iframe[name="${f}"]`)))switch(d){case 5:SS(e,f);break;case 8:TS(b,e,c);break;case 1:US(b,e,c);break;case 6:case 7:VS(d,c,e);break;case 9:WS(a,
e);break;case 10:XS(e,c)}}}},bT=function(a){a.o=a.querySelector(".devsite-article-body");a.o&&(ZS(a),a.v=[]);a.g&&a.g.disconnect();a.h.clear();$S(a);if(!document.body.hasAttribute("appearance")){var b=[...a.querySelectorAll("picture > source.devsite-dark-theme")];for(var c of b){b=c.closest("picture");const d=b.querySelector("img");b.querySelectorAll("source:not(.devsite-dark-theme)").length?c.remove():b&&d&&b.replaceWith(d)}}c=Array.from(a.querySelectorAll(".devsite-nav-title, .devsite-page-title, td > code, th > code"));
"docs"===document.body.getAttribute("layout")&&a.o&&(b=Array.from(a.o.querySelectorAll("h1, h2, h3, h4, h5, h6")),c.push(...b));a.h.clear();a.h=new Set(c);if(_ds.G().hash){c=new _ds.vH;for(const d of a.h)_ds.uH(c,d,QS)}else aT(a,a.h);a.dispatchEvent(new CustomEvent("devsite-content-updated",{bubbles:!0}))},$S=function(a){Array.from(a.getElementsByTagName("table")).forEach(b=>{if(!b.parentNode.classList.contains("devsite-table-wrapper")){var c=document.createElement("div");c.classList.add("devsite-table-wrapper");
b.classList.contains("full-width")&&(c.classList.add("devsite-full-width-table"),b.classList.remove("full-width"));_ds.Yh(c,b);c.appendChild(b)}})},RS=async function(a,b){const c=cT(a,b.source);if(c){const e="goog_"+_ds.Eh++;c.setAttribute("name",e);var d=_ds.Fl(3);d=_ds.Xb(d,2,e);(b=b.source)&&b.postMessage(_ds.df(d),"*");(b=document.body.getAttribute("appearance"))&&dT(c,b);a.v.push(c)}},SS=async function(a,b){const c=_ds.Qh(document).y,d=_ds.Xe(a,4);a=_ds.Xe(a,3);b=_ds.fi(b);d&&b.setAttribute("width",
`${d}px`);a&&b.setAttribute("height",`${a}px`);window.requestAnimationFrame(()=>{window.scrollTo(_ds.Qh(document).x,c)})},TS=async function(a,b,c){b=_ds.Gl(_ds.Fl(8),_ds.y(b,8));c=_ds.Xb(b,6,c.toString());(a=a.source)&&a.postMessage(_ds.df(c),"*")},US=async function(a,b,c){b=_ds.Gl(_ds.Fl(2),_ds.y(b,8));c=_ds.Xb(b,7,`${c.search}${c.hash}`);(a=a.source)&&a.postMessage(_ds.df(c),"*")},VS=async function(a,b,c){const d=c.getTitle();b=new URL(c.getUrl(),b.origin);b=`${window.location.origin}${window.location.pathname}${b.search}${b.hash}`;
6===a?window.history.pushState({},d,b):window.history.replaceState({},d,b)},WS=async function(a,b){const c=_ds.y(b,9);let d;try{d=JSON.parse(_ds.y(b,10))}catch(e){console.warn("Event data from Framebox is not valid JSON.",a);return}"analyticsEvent"===c?a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:d,bubbles:!0})):"cloudtrackEvent"===c?a.dispatchEvent(new CustomEvent("devsite-analytics-observation-cloudtrack",{detail:{eventData:d},bubbles:!0})):"devsite-apix"===c&&a.dispatchEvent(new CustomEvent("devsite-apix-observation",
{detail:d,bubbles:!0}))},XS=async function(a,b){if(a=a.getUrl()){const c=new URL(a,b.origin);a.startsWith("#")||b.origin===c.origin&&b.pathname===c.pathname&&b.search===c.search?DevsiteApp.scrollToAnchor(c.hash,!0):DevsiteApp.fetchPage(c.href)}},cT=function(a,b){let c;Array.from(a.querySelectorAll("devsite-iframe iframe")).forEach(d=>{_ds.gi(d)===b&&(c=d)});return c},dT=function(a,b){var c=_ds.Fl(12);b=_ds.Xb(c,12,b);a&&a.contentWindow&&(a=a.contentWindow)&&a.postMessage(_ds.df(b),"*")},ZS=function(a){"full"===
document.body.getAttribute("layout")&&(a=a.o.querySelectorAll('h1[tabindex="0"],h2[tabindex="0"],h3[tabindex="0"],h4[tabindex="0"],h5[tabindex="0"],h6[tabindex="0"]'))&&Array.from(a).forEach(b=>{b.removeAttribute("tabindex")})},aT=function(a,b){a.g&&b.forEach(c=>{a.g.observe(c)})},eT=class extends _ds.F{constructor(){super();this.C=new _ds.H;this.D=new _ds.H;this.h=new Set;this.v=[];this.g=null;"IntersectionObserver"in window&&(this.g=new IntersectionObserver(a=>{for(const b of a)b.isIntersecting&&
(a=b.target,_ds.uH(new _ds.vH,a,QS),this.h.delete(a),this.g.unobserve(a))},{rootMargin:"100%"}))}connectedCallback(){this.C.listen(window,"message",a=>YS(this,a));this.C.listen(document.body,"devsite-appearance-updated",a=>{if((a=a.Z.detail.preference)&&this.v.length)for(const b of this.v)dT(b,a)});bT(this)}disconnectedCallback(){this.g&&this.g.disconnect();this.h.clear();_ds.I(this.C);_ds.I(this.D)}sb(a){a&&([".devsite-article",".devsite-content-data","devsite-content-footer","devsite-notification"].forEach(b=>
{_ds.$g(this,this.querySelector(b),a.querySelector(b))}),bT(this))}};eT.prototype.updateContent=eT.prototype.sb;eT.prototype.disconnectedCallback=eT.prototype.disconnectedCallback;eT.prototype.connectedCallback=eT.prototype.connectedCallback;try{window.customElements.define("devsite-content",eT)}catch(a){console.warn("devsite.app.customElement.DevsiteContent",a)};})(_ds_www);
