(function(_ds){var window=this;var pQ=function(){return(0,_ds.S)('<button class="devsite-book-nav-toggle" aria-haspopup="menu"><span class="material-icons devsite-book-nav-toggle-icon"></span></button>')},qQ=function(){return(0,_ds.S)('<div class="devsite-book-nav-blur"></div>')},rQ=function(a){a=a.Lq;a=_ds.Ky(new _ds.Gy("{NUMBER_OF_MATCHING_DESCENDANTS,plural,=1{{XXX_1} match}other{{XXX_2} matches}}"),{NUMBER_OF_MATCHING_DESCENDANTS:a,XXX_1:_ds.T(_ds.jq(1)),XXX_2:_ds.T(_ds.jq(a))});return(0,_ds.S)('<span class="devsite-nav-filter-match-count"> (<mark>'+
a+"</mark>)</span>")};var sQ="onpointerover"in window?"pointerover":"mouseover",tQ=function(a){const b=0<a.querySelectorAll(".devsite-nav-item").length,c=document.querySelector("#devsite-hamburger-menu");c&&(b?c.removeAttribute("visually-hidden"):_ds.E(a,"visually-hidden","",c))},BQ=function(a){a.eventHandler.listen(a,"click",b=>void uQ(a,b));a.eventHandler.listen(a,"keypress",b=>{13===b.keyCode&&uQ(a,b)});a.eventHandler.listen(a,[sQ,"focusin"],b=>void vQ(a,b));a.eventHandler.listen(document.body,"devsite-sitemask-hidden",
()=>{a.h&&(wQ(a,"_book")?a.removeAttribute("top-level-nav"):_ds.E(a,"top-level-nav",""))});a.eventHandler.listen(document.body,"devsite-page-loaded",()=>void a.H.xa());a.eventHandler.listen(a,"devsite-content-updated",()=>{a.H.xa()});a.eventHandler.listen(a,"scroll",()=>{_ds.E(a,"user-scrolled","")});a.eventHandler.listen(a.qb,"click",()=>{xQ(a)});a.g&&(a.eventHandler.listen(a.g,"keyup",()=>void a.M.xa()),a.eventHandler.listen(a.g,"focus",()=>void yQ(a,"focus")));a.D&&a.eventHandler.listen(a.D,["click",
"keydown"],b=>{if("click"===b.type||13===b.keyCode||27===b.keyCode){a.g&&(a.g.value="",a.g.focus());let c;null==(c=a.D)||c.classList.add("hidden");zQ(a);AQ(a);yQ(a,b.type)}})},DQ=function(a,b=a,c=!0){b=Array.from(b.querySelectorAll(".devsite-nav-title"));a.C=new Set(b);if(!_ds.G().hash&&c)CQ(a,a.C);else{c=new _ds.vH;for(const d of a.C)_ds.uH(c,d)}},EQ=async function(a){const b=await _ds.x();for(const c of a.C)b.unregisterIntersectionForElement(c)},uQ=function(a,b){if(!b.defaultPrevented){var c=b.target;
"devsite-close-nav"===c.getAttribute("id")&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.hasAttribute("top-level-nav")?a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})):_ds.E(a,"top-level-nav",""));if(c.hasAttribute("menu")){var d=c.getAttribute("menu");d&&wQ(a,d)&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.removeAttribute("top-level-nav"))}var e=c.closest(".devsite-expandable-nav");if(e&&(d=c.closest(".devsite-nav-title, .devsite-nav-toggle"))){let f=
b.target,g,h;if(!(null==(g=f)?0:null==(h=g.closest(".devsite-nav-title"))?0:h.hasAttribute("href"))){for(b="click"===b.type||"touchend"===b.type;f&&f!==e;){if(f.classList.contains("devsite-nav-title-no-path")&&b){f.blur();break}f=f.parentNode}e.querySelector(".devsite-nav-section")&&(b=e.classList.toggle("expanded"),(e=e.querySelector(".devsite-nav-title"))&&_ds.E(a,"aria-expanded",`${b}`,e))}if(d.matches(".devsite-nav-toggle"))return}c.closest(".devsite-nav-title-no-path")||(a.h&&(d=a.h.querySelector("[menu=_book]"))&&
d.contains(c)&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})),(c=c.closest("a.devsite-nav-title"))&&!c.classList.contains("devsite-nav-has-children")&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})))}},vQ=function(a,b){b.defaultPrevented||(b=_ds.pi(b.target,c=>c instanceof HTMLAnchorElement&&c.hasAttribute("href")||c===a,!0),b!==a&&_ds.ad(b,_ds.$c(_ds.lj(b.href).href)))},xQ=async function(a){var b=document.documentElement.scrollHeight-document.documentElement.clientHeight;
const c=b?document.documentElement.scrollTop/b:0;_ds.Ik(a.eventHandler,a,_ds.qf,()=>{a.removeAttribute("animatable");a.background.removeAttribute("animatable");a.o.removeAttribute("animatable")});_ds.E(a,"animatable","");b=_ds.Jc(a.j`animatable`);b(a.background,"animatable","");b(a.o,"animatable","");a.hasAttribute("collapsed")?(_ds.E(a,"aria-expanded","true",a.qb),_ds.E(a,"aria-label","Hide side navigation",a.qb),_ds.E(a,"data-title","Hide side navigation",a.qb),a.removeAttribute("collapsed"),FQ(a,
"Expanded book nav")):(a.qb.removeAttribute("aria-expanded"),_ds.E(a,"aria-label","Show side navigation",a.qb),_ds.E(a,"data-title","Show side navigation",a.qb),_ds.E(a,"collapsed",""),FQ(a,"Collapsed book nav"));await _ds.sj();b=document.documentElement.scrollHeight-document.documentElement.clientHeight;document.documentElement.scrollTop=Math.round(c*b)},yQ=function(a,b){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",action:b,label:"focus"===
b?"devsite-book-nav-filter input":"devsite-book-nav-filter filter-clear-button"},bubbles:!0}))},GQ=function(a){a.F=Array.from(a.querySelectorAll(".devsite-mobile-nav-bottom .devsite-nav-list[menu=_book] .devsite-nav-item:not(.devsite-nav-heading)"))},IQ=function(a){const b=_ds.G().searchParams.get("nf");a.g&&b&&(a.g.value=b,HQ(a))},HQ=function(a){if(a.F.length){zQ(a);AQ(a);var b,c,d=null==(b=a.g)?void 0:null==(c=b.value)?void 0:c.trim().toLowerCase();if(d){var e;null==(e=a.D)||e.classList.remove("hidden");
for(const g of a.F){c=g.querySelectorAll(".devsite-nav-text");b=g.classList.contains("devsite-nav-expandable");var f=e=!1;a=0;let h,k;if(d&&b&&(null==(h=g.querySelector(".devsite-nav-text"))?0:null==(k=h.textContent)?0:k.toLowerCase().includes(d)))f=e=!0;else for(const l of c){let m;d&&(null==(m=l.textContent)?0:m.toLowerCase().includes(d))&&(e=!0,++a)}if(!0===e){g.classList.remove("hidden");if(f){c=Array.from(g.querySelectorAll(".devsite-nav-item"));for(const l of c){l.classList.remove("hidden");
let m;d&&(null==(m=l.textContent)?0:m.toLowerCase().includes(d))&&++a}}c=void 0;(f=g.querySelector(".devsite-nav-text"))&&(e=null==(c=f.textContent)?void 0:c.replace(new RegExp(`(${d})`,"ig"),"<mark>$1</mark>"))&&_ds.Hc(f,_ds.Pg.g(e))}b&&0<a&&(b=g.querySelector(".devsite-nav-text"))&&(a=_ds.O(rQ,{Lq:a}),b.appendChild(a))}}else null==(f=a.D)||f.classList.add("hidden")}},zQ=function(a){for(const b of a.F){let c;b.classList.toggle("hidden",!(null==(c=a.g)||!c.value))}},AQ=function(a){if(a.querySelector("mark")){var b=
[...a.querySelectorAll(".devsite-nav-text > .devsite-nav-filter-match-count")];for(const c of b)c.remove();a=[...a.querySelectorAll(".devsite-nav-text > mark")];for(const c of a){a=c.parentElement;let d;b=null==(d=a)?void 0:d.textContent;a&&b&&_ds.Hc(a,_ds.Pg.g(b))}}},CQ=async function(a,b){if(a.v){var c=await _ds.x(),d=new _ds.vH,e=f=>{f=f.target;_ds.uH(d,f);a.C.delete(f);c.unregisterIntersectionForElement(f)};for(const f of b)try{c.registerIntersectionForElement(f,e)}catch(g){e({target:f})}}},wQ=
function(a,b){let c=!1;if(a.h)for(const d of a.h.querySelectorAll("[menu]"))d.getAttribute("menu")===b?(d.removeAttribute("hidden"),c=!0):_ds.E(a,"hidden","",d);return c},JQ=function(a,b=a){b||(b=a);for(const c of b.querySelectorAll(".devsite-nav-active"))c.classList.remove("devsite-nav-active");a=_ds.yj(_ds.G().pathname);a=`[href="${_ds.lj(a).href}"], [href="${a}"],
        [alt-paths~="${a}"]`;for(const c of b.querySelectorAll(a))c.classList.add("devsite-nav-active")},KQ=function(a,b=a){b||(b=a);if(a=b.querySelector(".devsite-mobile-nav-bottom"))for(a=a.querySelector(".devsite-nav-active");a&&a.parentElement&&a.parentElement!==b;)a.matches(".devsite-expandable-nav:not(.expanded)")&&a.classList.add("expanded"),a=a.parentElement},MQ=async function(a){a.v&&(a.removeAttribute("user-scrolled"),await _ds.sj(),await LQ(a),await a.O,await _ds.x(),await _ds.sj(),await LQ(a))},
LQ=async function(a){if(a.v&&a.h){await _ds.x();var b=a.h.querySelector(".devsite-nav-active");b&&(a.hasAttribute("user-scrolled")||await NQ(a,b))}},NQ=async function(a,b){if(a.v){var c=a.hasAttribute("user-scrolled");a.scrollTop=_ds.Yk(b,a,!0).y;await _ds.sj();c&&_ds.E(a,"user-scrolled","")}},FQ=function(a,b){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",action:"click",label:b},bubbles:!0}))},OQ=class extends _ds.F{constructor(){super();
this.v=!1;this.D=this.g=this.G=this.h=null;this.F=[];this.eventHandler=new _ds.H;this.K=()=>{};this.C=new Set;this.J=this.V=!1;this.background=document.createElement("div");this.background.classList.add("devsite-book-nav-bg");this.qb=_ds.O(pQ);this.o=_ds.O(qQ);this.O=new Promise(a=>{this.K=a});this.H=new _ds.Ek(()=>{this.v&&tQ(this)},20);this.M=new _ds.Ek(()=>{HQ(this)},20)}static get observedAttributes(){return["collapsed","fixed","hidden"]}async connectedCallback(){this.v=!0;_ds.Xg(this,this.j`animatable`,
this.j`aria-expanded`,this.j`aria-label`,this.j`collapsed`,this.j`data-title`,this.j`fixed`,this.j`has-book-nav`,this.j`hidden`,this.j`top-level-nav`,this.j`user-scrolled`,this.j`visually-hidden`);_ds.Yh(this.background,this);this.hasAttribute("hidden")&&(_ds.E(this,"hidden","",this.qb),_ds.E(this,"hidden","",this.o));const a=await _ds.x();if(this.V=a.hasMendelFlagAccess("BookNav","enable_collapsible_book_nav")){let b;null==(b=this.parentElement)||b.insertBefore(this.qb,this.nextSibling);_ds.E(this,
"aria-label","Hide side navigation",this.qb);_ds.E(this,"data-title","Hide side navigation",this.qb);_ds.E(this,"aria-expanded","true",this.qb);let c;null==(c=this.parentElement)||c.insertBefore(this.o,this.nextSibling)}if(this.J=a.hasMendelFlagAccess("BookNav","enable_book_nav_filtering"))if(this.G=this.querySelector(".devsite-book-nav-filter"))this.g=this.G.querySelector("input[type=text]"),this.D=this.G.querySelector(".filter-clear-button"),GQ(this),IQ(this);tQ(this);BQ(this);await this.init();
DQ(this)}disconnectedCallback(){this.v=!1;_ds.I(this.eventHandler);EQ(this);this.C.clear();var a=document.querySelector("#devsite-hamburger-menu");a&&_ds.E(this,"visually-hidden","",a);a=[this.background,this.qb,this.o];for(const b of a)b&&_ds.$h(b);this.removeAttribute("animatable");this.background.removeAttribute("animatable");this.o.removeAttribute("animatable");this.o.style.removeProperty("--devsite-js-book-nav-scrollbar-width")}attributeChangedCallback(a){"hidden"===a&&this.dispatchEvent(new CustomEvent(this.hasAttribute("hidden")?
"devsite-element-hidden":"devsite-element-visible",{bubbles:!0}));if("hidden"===a||"collapsed"===a){var b=document.querySelector(".devsite-main-content");b&&(this.hasAttribute("collapsed")||this.hasAttribute("hidden")?b.removeAttribute("has-book-nav"):_ds.E(this,"has-book-nav","",b))}if("fixed"===a||"hidden"===a||"collapsed"===a){b=this.hasAttribute(a);const c=[this.background,this.qb,this.o];for(const d of c)d&&(b?_ds.E(this,a,"",d):d.removeAttribute(a))}"fixed"===a&&this.K()}async init(a=!0){if(this.v){this.o.style.setProperty("--devsite-js-book-nav-scrollbar-width",
`${this.offsetWidth-this.clientWidth}px`);this.h=this.querySelector(".devsite-mobile-nav-bottom");_ds.E(this,"top-level-nav","");this.h&&this.h.querySelector("[menu=_book]")&&this.removeAttribute("top-level-nav");0===this.children.length&&_ds.E(this,"hidden","");if(this.background)for(const b of["hidden","fixed","animatable"])this.hasAttribute(b)&&_ds.E(this,b,"",this.background);!this.hasAttribute("hidden")&&a?(JQ(this),KQ(this),await MQ(this)):(await _ds.sj(),await LQ(this))}}async sb(a){a?(a=a.querySelector("nav")||
null,JQ(this,a),KQ(this,a),a&&(await EQ(this),this.C.clear(),DQ(this,a,!1)),_ds.$g(this,this.querySelector("nav"),a)):_ds.Xh(this);if(this.J&&(GQ(this),this.g)){this.g.value="";let b;null==(b=this.D)||b.classList.add("hidden");IQ(this)}await _ds.sj();await this.init(!1)}};OQ.prototype.updateContent=OQ.prototype.sb;OQ.prototype.attributeChangedCallback=OQ.prototype.attributeChangedCallback;OQ.prototype.disconnectedCallback=OQ.prototype.disconnectedCallback;OQ.prototype.connectedCallback=OQ.prototype.connectedCallback;try{window.customElements.define("devsite-book-nav",OQ)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteBookNav",a)};})(_ds_www);
