(function(_ds){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var DW=_ds.ih(function(){return!_ds.ce||0<=_ds.Ia(_ds.JK,9)}),EW=_ds.ih(function(){return _ds.ge||_ds.de||_ds.fe&&0<=_ds.Ia(_ds.JK,10)||_ds.ce&&0<=_ds.Ia(_ds.JK,10)}),GW=function(a,b){DW()&&(b=EW()?"translate3d("+b+"px,0px,0px)":"translate("+b+"px,0px)",_ds.Ok(a,FW(),b))},FW=_ds.ih(function(){return _ds.ce&&9==_ds.ze?"-ms-transform":"transform"});var JW=function(a){a.h=HW(a,".devsite-top-logo-row-wrapper-wrapper");a.g=HW(a,".devsite-collapsible-section");a.o=HW(a,".devsite-doc-set-nav-row");a.setAttribute("top-row--height",`${a.h}`);a.setAttribute("bottom-row--height",`${a.g}`);a.setAttribute("bottom-tabs--height",`${a.o}`);IW(a)},IW=function(a){const b=a.querySelector(".devsite-collapsible-section");a.offset>=a.g&&!a.hasAttribute("bottom-row--hidden")?a.setAttribute("bottom-row--hidden",""):a.offset<a.g-a.o&&a.hasAttribute("bottom-row--hidden")&&
a.removeAttribute("bottom-row--hidden");b&&a.offset!==a.G&&(_ds.Ok(b,"transform",`translate3d(0, -${a.offset}px, 0)`),KW(a),a.G=a.offset);document.body.style.setProperty("--devsite-js-header-height",`${a.v()}px`)},LW=function(a){var b=a.querySelector(".devsite-top-logo-row-middle");const c=a.querySelector("devsite-search"),d=a.querySelector(".devsite-search-background");if(b&&c&&d){_ds.I(a.D);a.C&&window.cancelAnimationFrame(a.C);c.removeAttribute("transition");a.removeAttribute("search-expanded");
var e=new _ds.vh(b.offsetWidth,b.offsetHeight);b=new _ds.vh(c.offsetWidth,c.offsetHeight);var f=_ds.gl(c,"margin"),g="rtl"===document.documentElement.getAttribute("dir")?1:-1,h=(e.width-f.left-f.right)/b.width;e=(e.width-(b.width+f.left+f.right))*g;var k=(f=a.hasAttribute("search-active"))?e:0,l=f?h:1;_ds.Ok(d,{opacity:1,width:`${b.width}px`,height:`${b.height}px`});GW(c,a.hasAttribute("search-active")?0:e);_ds.Ik(a.D,d,_ds.qf,()=>{const m=a.querySelector("devsite-search"),p=a.querySelector(".devsite-search-background");
p&&(p.style.opacity="0");m&&(m.removeAttribute("transition"),GW(m,0),a.hasAttribute("search-active")?a.setAttribute("search-expanded",""):a.removeAttribute("search-expanded"))});a.C=window.requestAnimationFrame(()=>{c.setAttribute("transition","");if(DW()){var m=EW()?"scale3d("+l+",1,1)":"scale("+l+",1)";_ds.Ok(d,FW(),m)}GW(c,k)})}},MW=async function(a,b){if(a.hasAttribute("billboard")){var c=a.querySelector("devsite-search"),d=a.querySelector("devsite-search input.devsite-search-query");a=a.querySelector(".devsite-header-billboard-search devsite-search");
var e=null==a?void 0:a.querySelector("input.devsite-search-query");c&&d&&a&&e&&(b?(c.removeAttribute("disabled"),document.activeElement===e&&(await _ds.sj(),d.focus()),a.setAttribute("disabled","")):(a.removeAttribute("disabled"),document.activeElement===d&&e.focus(),c.setAttribute("disabled","")))}},OW=function(a){a.eventHandler.listen(a,"devsite-search-toggle",b=>{b=b.Z;_ds.qi(b.target,null,"devsite-top-logo-row-middle")&&(b.detail.active?a.setAttribute("search-active",""):a.removeAttribute("search-active"))});
a.eventHandler.listen(document.body,"devsite-sitemask-hidden",()=>document.body.removeAttribute("devsite-book-nav--open"));a.eventHandler.listen(window,"resize",()=>NW(a));a.eventHandler.listen(document.body,["devsite-page-loaded","devsite-content-updated"],()=>{NW(a)});a.eventHandler.listen(a,"click",b=>{b.defaultPrevented||"devsite-hamburger-menu"!==b.target.getAttribute("id")||(b.preventDefault(),b.stopPropagation(),document.body.setAttribute("devsite-book-nav--open",""),a.dispatchEvent(new CustomEvent("devsite-sitemask-show",
{bubbles:!0})))})},PW=function(a){if(!a.querySelector(".devsite-search-background")&&(a=a.querySelector(".devsite-top-logo-row-middle"))){const b=document.createElement("div");b.classList.add("devsite-search-background");b.style.opacity="1";a.appendChild(b)}},KW=function(a){0===a.g?a.setAttribute("no-lower-row",""):a.removeAttribute("no-lower-row");a.querySelector(".devsite-header-billboard")?a.setAttribute("billboard",""):a.removeAttribute("billboard")},NW=function(a){window.requestAnimationFrame(()=>
a.J.xa())},HW=function(a,b){return(a=a.querySelector(b))?a.getBoundingClientRect().height:0},QW=function(a,b){for(var c=0;c<b.attributes.length;++c){var d=b.attributes.item(c);a.hasAttribute(d.name)||b.removeAttribute(d.name)}for(c=0;c<a.attributes.length;++c)d=a.attributes.item(c),b.setAttribute(d.name,d.value)},RW=function(a,b,c){b=b.querySelector(c);c=a.querySelector(c);b&&c&&(a.updated=!0,_ds.$g(a,c,b))},SW=class extends _ds.F{constructor(){super(...arguments);this.eventHandler=new _ds.H;this.G=
-1;this.D=new _ds.H;this.C=0;this.F=new MutationObserver(()=>JW(this));this.J=new _ds.Ek(()=>{JW(this);KW(this)},15);this.authUser=void 0;this.offset=this.o=this.g=this.h=0;this.updated=!1}static get observedAttributes(){return["offset","search-active","bottom-row--hidden"]}attributeChangedCallback(a,b,c){switch(a){case "offset":this.offset=Number(this.getAttribute("offset")||"")||0;IW(this);break;case "search-active":LW(this);break;case "bottom-row--hidden":a=null!==c,b=this.querySelector("devsite-search input.devsite-search-query"),
c=this.querySelector(".devsite-header-billboard-search devsite-search input.devsite-search-query"),b&&c&&(a?b.value=c.value:c.value=b.value),MW(this,a)}}connectedCallback(){OW(this);PW(this);KW(this);JW(this);this.F.observe(this,{childList:!0,subtree:!0});IW(this);const a=_ds.G();this.authUser=_ds.Ui(_ds.Vi(a.href),"authuser")}disconnectedCallback(){_ds.I(this.eventHandler);this.F.disconnect()}v(){return this.h+this.g-this.offset}H(){return this.h+this.g}sb(a){this.updated=!1;if(a){RW(this,a,".devsite-header-upper-tabs");
RW(this,a,".devsite-collapsible-section");RW(this,a,".devsite-product-name-wrapper");RW(this,a,"devsite-language-selector");RW(this,a,"devsite-shell-activate-button");var b=a.querySelector("devsite-search"),c=this.querySelector("devsite-search");b&&c&&QW(b,c);c=a.querySelector("devsite-user");b=this.querySelector("devsite-user");c&&b&&(QW(c,b),c=_ds.G(),c=_ds.Ui(_ds.Vi(c.href),"authuser"),c!==this.authUser&&(this.authUser=c,b.refresh()));_ds.$g(this,this.querySelector("cloudx-additional-tabs"),a.querySelector("cloudx-additional-tabs"),
this.querySelector(".devsite-top-logo-row-middle"));_ds.$g(this,this.querySelector(".devsite-header-link"),a.querySelector(".devsite-header-link"),this.querySelector("devsite-language-selector"))}!this.updated&&a&&(_ds.Xh(this),this.appendChild(a));PW(this);NW(this)}};try{window.customElements.define("devsite-header",SW)}catch(a){console.warn("devsite.app.customElement.DevsiteHeader",a)};})(_ds_www);
